### ISSUE TITLE
Publication page

### ISSUE THREAD

**Issue by ipeirotis** [ipeirotis-org/scholar_v2#7]
We should create a page showing the statistics of an individual publication that is listed for an author.

We can get the details of the publication from the author data, then use the `fill` command to get the number of citations per year. Based on these numbers, we can calculate the percentile values for the paper, using the cumulative number of citations.

The main plot can have two y-axis: The primary shows the total number of citations and the secondary shows the percentile of the paper over time.

We should probably break this into three parts: The analytics for the calculation, creating the API for returning the results, and the HTML page that shows the results.

**Comment by Jackrao-Git** [comment]
In Progress

**Comment by ipeirotis** [comment]
Basic data is now there, needs a plot showing citations over time, plus percentiles over time.
